spring.application.name=sb-ecommerce

#spring.h2.console.enabled = true
#spring.datasource.url = jdbc:h2:mem:test

spring.datasource.url= jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password =Madhu#1053

spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
# Above one Tell Hibernate which database you are using, so it can generate the correct SQL for that database.



# Add relevant dependency in pom.xml
# This is for postgreSQL
#spring.datasource.url= jdbc:postgresql://localhost:5432/ecommerce
#spring.datasource.username=postgres
#spring.datasource.password =Madhu#1053  (which gave while postgres download)

#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true
#spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect   // Tell Hibernate which database you are using, so it can generate the correct SQL for that database.



project.image=images/


#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format-sql = true
#spring.jpa.hibernate.ddl-auto = create / create-drop / update


spring.app.secretToken = springSecurity12390l0ijhtjhgfdsrthbvcddftyhgtfre4565
spring.app.expirationTimeMs = 3600000

spring.ecom.app.jwtCookieName = SpringBootEcom

#logging.level.org.springframework = DEBUG
#logging.level.org.hibernate.SQL = DEBUG
#logging.level.org.springframework.security = DEBUG
#logging.level.com.ecommerce.project = DEBUG